### ISSUE TITLE
seedsファイルの修正

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#101]
https://github.com/nsuzuki7713/a6s-cloud-front/pull/66 から発生したissueです。
テストデータのユーザが@付いているので削除する。
後は全体的にデータを整理するanalysis_resultsとかは1件のみでも良いかもしれない。

**Comment by nsuzuki7713** [comment]
コナン見ながら、やりまーす笑

**Comment by TsutomuNakamura** [comment]
ありがとうございます。自分の黒歴史(?)seed ファイル、修正お願いします🙇‍♂️
