### ISSUE TITLE
バリデーションで不正検知したときに返すレスポンスをJSONにする

### ISSUE THREAD

**Issue by tokidrill** [nsuzuki7713/a6s-cloud-backend#104]
#46 でAnalysisRequestsControllerのパラメータにバリデーションをかけたが、
バリデーションに引っかかった時、Laravelでは自動でリダイレクトをレスポンスする。
SPAではJSONでレスポンスするべきだが、そのためにはバリデーションをカスタマイズするしかなさそうなので、頑張る。

参考になりそうな記事↓
https://qiita.com/rana_kualu/items/77134af5477d27bf2cc2

**Comment by nsuzuki7713** [comment]
昨日プルリクで動作確認しましたが、エラーコードが戻ってきていました！！
もしかして、すでにできている🤔
https://github.com/nsuzuki7713/a6s-cloud-backend/pull/100

**Comment by tokidrill** [comment]
むむむ、まじですか？？
そしたらこれは保留にしておきますので、日曜日に一緒に確認させてください！

**Comment by tokidrill** [comment]
ミーティングで正常な動作を確認したので対応しない方針として、本件クローズします。
