### ISSUE TITLE
変数名の書き方を揃える(スネークケース or キャメルケース)

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#110]
スネークケースかキャメルケースか、a6s-cloud-backend プロジェクトの中で統一したいです。
今までのSlack 等の会話内容を考慮するとスネークケースか！？

**Comment by nsuzuki7713** [comment]
考慮する所は下記ですかね？？
フロントを考えるとAPIはキャメルがいいですが検討必要そうです。
明日のMTGの議題に入れておきます！！
- バックエンド
- API
- フロントエンド

**Comment by tokidrill** [comment]
基本はLaravelの命名規則に従う↓
https://laraweb.net/knowledge/942/

ただし、フロント側の変数はキャメルとしたいため、フロントにレスポンスする変数は、
スネーク → キャメル変換を通してからレスポンスする。

**Comment by tokidrill** [comment]
#115 起票したので本件はクローズします。
