### ISSUE TITLE
変数を命名規則に従って書き直す

### ISSUE THREAD

**Issue by tokidrill** [nsuzuki7713/a6s-cloud-backend#115]
基本的に既にLaravelの命名規則に従っているが、再確認する。
JSONレスポンスする変数はスネーク→キャメル変換を通してレスポンスするように変更する。

参考 : #110

**Comment by nsuzuki7713** [comment]
[Laravel5+でレスポンスJSONのキーをcamelCaseにする
](https://qiita.com/grohiro/items/34984cf226f7a3593a99) これ使えるかな🤔
