### ISSUE TITLE
heroku の調査

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#116]
heroku にa6s-cloud-backend をデプロイできるか調査する。

**Comment by TsutomuNakamura** [comment]
ひとまずDB なし、画像作成なしのheroku ができました…(URL はSlack で連携しておきます)。
現状は適当なPOST を投げるとOK と返すだけのアプリで、まだ色々考える事がありそうです...。
ブランチは`deploy_a6s_on_heroku` としてpush しておきました。まだマージできるものではありません😭

### ●MySQL
デフォルトで入っていない。なので追加する必要がある。
addons で追加する感じでいけるか？
https://devcenter.heroku.com/articles/cleardb
Python についても同じ。

### ●GitHub 連携においてはgit submodule 非対応
できそう。しかしgit submodule に対応していないので、考慮の必要あり。GitHub 連携する場合はbatch, font のリポジトリをどのように持ってくるか考える必要ありそう。
https://devcenter.heroku.com/articles/github-integration
手動でpush heroku する場合はgit submodule やってくれる。

### ●Docker コンテナとして配備したい場合
基本ファイルシステムは揮発性。なのでDB ファイル類は置けない？あとDocker のlink に対応していないのであるContainer でPHP、あるContainer でMySQL という構成はできなさそう(できても揮発せいなので…)。
これをやる場合はアプリはContainer、DB はどこか他のインスタンス等にする必要ありそう
https://devcenter.heroku.com/articles/container-registry-and-runtime

### ●.env ファイルが作成できない
post script のようなものはできるか？git push heroku したあとに.env ファイルを作成するような処理ができれば嬉しい。
できないのであれば.env を無理やりコミットする(.gitignore に.env 含まれている)。
もしくは`heroku config:set KEY=VALUE` と.env 内に書かれている変数をすべてコマンドで設定する？

### ●Twitter API のキー
```
heroku config:set CONSUMER_KEY=foooooooooooooo
heroku config:set CONSUMER_SECRET=baaaaaaaaaaaaaar
...
```
とコマンド設定すれば.env にダミー値が設定されていても上書きできる。本番はこれで設定するのが良いか？DB 接続先やパスワードも同様に。

### ●リポジトリのroot にcomposer.json が来る構成になっていない
なので、heroku にpush する場合はトリッキーなpush の仕方をする必要がある。
リポジトリの構成を見直せばもっとシンプルになりそう。
```
$ # a6s-cloud ディレクトリだけpush する
$ git subtree push --prefix a6s-cloud heroku master
```

### ●ロギング
logger コマンドでログが出力されない。デバッグ時はerror_log() 関数で標準出力(heroku logs) で見て確認する必要がありそう。また本番時はファイルに出力する方法を考える必要がある

### ●構築手順記録
```
$ cd a6s-cloud-backend
$ heroku login
## 
$ git checkout -b deploy_a6s_on_heroku
$ echo "web: vendor/bin/heroku-php-apache2 public/" > a6s-cloud/Procfile
$ git add a6s-cloud/Procfile
$ git commit -m "Added Procfile for heroku"
$ heroku create
-> インスタンス名取れる。忘れた場合はheroku config
$ # 依存関係が複雑なのでlaradock コンテナ上でLaravel API_KEY 発行
$ ./build.sh
$ (cd laradock && docker-compose exec workspace bash -c 'cd /var/www/a6s-cloud && php artisan key:generate --show')
-> base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ heroku config:set APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ # a6s-cloud ディレクトリにpackage.json も入っているので、
$ # heroku がNode.js プロジェクトと間違えないように明示的に指定
$ heroku buildpacks:set heroku/php
$ # heroku はroot ディレクトリにcomposer.json が無いとPHP プロジェクトを認識できないため
$ # a6s-cloud ディレクトリのみデプロイする
$ git subtree push --prefix a6s-cloud heroku master
$ # https://foo-bar-xxxxxx.herokuapp.com にWeb ブラウザでアクセスするとトップページは見れる
$ # もしくはheroku open を実行する
$ heroku open
```

明日あたり、DBやPython あたり見ていきます。

**Comment by nsuzuki7713** [comment]
進捗ありがとうございます！！
ある程度調査して、大変そうで時間が掛る場合はまずはEC2に建てる形でも大丈夫です🙋‍♂️

**Comment by TsutomuNakamura** [comment]
コメントありがとうございます。了解です！明日もう少し調べてみて全然進みそうになければそちらの方で検討をしてみようと思います🤩

**Comment by TsutomuNakamura** [comment]
進捗:
一応、デモレベルにはできたかもですが…かなり制限付きです(詳細はSlack で連携します)。
そして、新たに出てきた課題点は以下の通り。

### ●heroku のファイルシステムは、保存されたファイルがいつまでも残っていることを保障してくれない
解析依頼を出して画像ファイルを作成しても、それがいつまでも保存されることを保障してくれない。
heroku を使い続けるのであれば、Storage としてAWS を使うなどの対応が必要そう。

### ●メモリが限られている
Word Cloud が思いのほか、メモリを消費するのでheroku 無料プランで動かすにはかなり厳しい。
数百tweet があるようなハッシュタグは無理(例えば"令和"とか)。

```
2019-05-01T07:51:50.432995+00:00 heroku[web.1]: Process running mem=745M(145.6%)
2019-05-01T07:51:50.432995+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-01T07:52:08.578336+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/v1/AnalysisRequests" host=young-oasis-94247.herokuapp.com request_id=b414f01f-d64b-4090-b836-f7b388cee912 fwd="114.167.186.176
" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https
```

curl などから、シンプルなリクエストをそっと投げてあげて見てください。

ちょっと明日あたり、デモのための期間限定的にEC2 なりに建ててみようと思います…。

**Comment by nsuzuki7713** [comment]
ありがとうございます！！やはり課題点は結構ありますね。
一旦herokuの調査はこれでクローズで良さそうですかね！！

**Comment by TsutomuNakamura** [comment]
ですね！クローズしておきます。
無料プランでは軽いCRUD とかにはOK そうですが、大量tweet や解析はお金払えということですね。
また別の環境にデモサイトは構築するようにします👍。
