### ISSUE TITLE
Word Cloud API (Python 版)を導入する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#12]
なおとさん謹製のPython 版Word Cloud API をDocker コンテナに取り入れる。

**Comment by TsutomuNakamura** [comment]
batch はこのリポジトリ

https://github.com/nsuzuki7713/a6s-cloud-batch

**Comment by TsutomuNakamura** [comment]
次はこれとりかかります🙋‍♂️。若干規模おおきくなりそうで、プルリクには数日かかるかもしれません。

**Comment by nsuzuki7713** [comment]
確かに、これは重たそうです。。よろしくお願いしますm(_ _)m

**Comment by TsutomuNakamura** [comment]
コメありがとうございます。
#51 に、バッチを叩くissue が立っているので、ここではlaradock のコンテナからa6s-cloud-batch をsubmodule として取り入れられた時点でプルリクしようと思います。

細かく切って、活性化して勢い維持する目的もあります💪(筋肉)
