### ISSUE TITLE
Tweet取得件数の上限値を決める

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#128]
現在は最大1000件の取得に制限していますが、上限値をどうするか。
勉強会のみのターゲットならば1000件あれば充分な気もします。
ただ、カンファレンスとかを考えれば5000件ぐらい🤔
もしくは時間制限で10分間で取れるだけとるとか？

皆さんはどう思われますかー？

https://github.com/nsuzuki7713/a6s-cloud-backend/blob/daf5d3e66a2a981b3d73762430e891200cc00fca/a6s-cloud/app/Services/TwitterClientService.php#L66

**Comment by TsutomuNakamura** [comment]
悩みどころですよね〜。
ひとまず最大5000 件にしても良いのかなぁ…とか個人的には考えています。もし、API 制限に引っかかったら調整できるように柔軟な設計にしておくとかどうでしょう？
その他、解析依頼出されたら同じハッシュタグでの解析はしばらく禁止するetc 制限かければAPI 制限と上手に付き合っていけるかもしれません🤔

**Comment by nsuzuki7713** [comment]
ありがとうございます🥳
一先ず5000件にしてみましょうか(word cloudが動くかな。。ゼロの執行人のときは10000件取得してword cloudの処理がタイムアウトしました笑)

>同じハッシュタグでの解析はしばらく禁止

→これもありますね！issue作成しておきます！

# 方針
Tweet取得件数の上限は5000件にしてみる。(ループ50回)

**Comment by TsutomuNakamura** [comment]
レスポンスありがとうございます。
> 一先ず5000件にしてみましょうか(word cloudが動くかな。。ゼロの執行人のときは10000件取得してword cloudの処理がタイムアウトしました笑)

なるほどぉ…😦。ですね。あとは我々開発者は自分でTwitter API キー取得してそっちでテストするようにするとかでもAPI リクエスト数を節約できると思います。
となると、自分は今からTwitter API キーの取得の仕方についてググることになりますが🙄(笑)

**Comment by nsuzuki7713** [comment]
一旦はa6s-cloudのアカウントで大丈夫です！！
正直、API リクエスト制限になるまで使われるイメージできていないです笑
(皆でゼロの執行人で叩くとやばいですが🙄)

**Comment by TsutomuNakamura** [comment]
了解です。そうですね！しばらくは今のAPI キー使わせてもらいます！

**Comment by nsuzuki7713** [comment]
これやっておきまーす
