### ISSUE TITLE
解析バッチ処理の作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#130]
最初は解析依頼フォームは公開せずに、自分達で勉強会情報を登録する予定
そのため、夜間とかでバッチ実行して解析処理を実行したい。

Laravelでタスクスケジュールがありそう👀

参考URL
[Laravel 5.5 タスクスケジュール
](https://readouble.com/laravel/5.5/ja/scheduling.html)
[Laravelでバッチ処理(Cron)を実行する](https://leben.mobi/blog/laravel5_batch/php/)

**Comment by TsutomuNakamura** [comment]
batch を保存しておくようなテーブルが必要かと思いますが、以下のような設計、シーケンスとかどうでしょうか？

### ●解析依頼リクエストが来た時にanalysis_timing の指定を解析して、以下のようなテーブルにデータをinsert する。

```
* analysis_batch_queue
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| Field               | Type                | Null | Key | Default           | Extra                                         |
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| id                  | bigint(20) unsigned | NO   | PRI | NULL              | auto_increment                                |
| analysis_start_date | datetime            | NO   |     | NULL              |                                               | 解析開始日時
| analysis_end_date   | datetime            | NO   |     | NULL              |                                               | 解析終了日時
| analysis_word       | varchar(255)        | YES  |     | NULL              |                                               | 解析ワード
| status              | tinyint(4)          | NO   |     | 0                 |                                               | 0: 実施前, 1: 実施中, 2: 成功, 3: 失敗, 4: キャンセル
| insert_date         | datetime            | NO   |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED                             |
| update_date         | datetime            | NO   |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED on update CURRENT_TIMESTAMP |
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
```

### ●batch 処理のシーケンス
* Laravel のバッチ(cron) でn 分単位でanalysis_batch_queue テーブルへアクセスする。`現在時刻 > analysis_start_date AND status = 0(or 3?)` をソートして取得
* 取得した件数分ループ(※1)
  * 該当するレコードの条件(analysis_word, analysis_start_date, analysis_end_date)で解析処理をする
  * analysis_batch_queue のステータスを更新する(2: 成功 or 3: 失敗)
  * Twitter API の上限がきたらbreak (処理しきれなかった分は次回batch タイミングで)
  * 取得したレコードがまだ残っている場合は(※1) のループを継続
* batch 終了

**Comment by TsutomuNakamura** [comment]
それかなおとさんが示してくれたリンクの中にあった、Laravel のキューを使うのもありかもしれません。
https://readouble.com/laravel/5.5/ja/queues.html

> * Laravel のバッチ(cron) でn 分単位でanalysis_batch_queue テーブルへアクセスする。`現在時刻 > analysis_start_date AND status = 0(or 3?)` をソートして取得

これやった時に、該当レコードをLaravel のキューにジョブとして入れておくという流れです。
ジョブがTwitter API の上限によりできない場合はしばらく時間おいてリトライできるような仕組みがあれば良いですが🤔

**Comment by nsuzuki7713** [comment]
テーブルは`analysis_results`を使用できそうな気がしました。(statusを見て挙動を変える)

batch 処理のシーケンスはイメージ通りです！！
Laravel のキューを使うより、自前実装したほうが拡張しやすそう🤔
今回の処理は一定間隔を開けて実行するのでキューよりbatchのイメージがあります🤔

**Comment by TsutomuNakamura** [comment]
確かに、それでは今回はanalysis_results 使うようにしましょうか。
ということはまず、解析リクエストが来た時にanalysis_timing を見てstatus 0 でanalysis_results レコードを登録するissue ができそうです👍

**Comment by nsuzuki7713** [comment]
ありがとうございます！！

`analysis_timing` に関しては仕様が曖昧になってきたのでもう一度再考したいですね。。
最初は僕らで必要データを手動insertしようと考えてました(status 0)
※データは頑張ってあつめる。connpass apiで取得したい。。

**Comment by TsutomuNakamura** [comment]
なるほど了解です。
仕様が曖昧なまま進めても後戻りする可能性高いと思うので、`analysis_timing` みてレコードを登録する処理実装よりもconnpass api でタグ取得してそれをstatus 0 でINSERT する処理実装の方を優先さたほうが良いと思いました。

**Comment by nsuzuki7713** [comment]
タスクは下記ですかね。

- connpass api でタグ取得してそれをstatus 0 でINSERT する処理実装 ← こちらは別issueに積む
- status 0のレコード解析するbatch処理(10分感覚とかで定期実行かAPI制限を見ながらなのか)

**Comment by TsutomuNakamura** [comment]
確かにそうです。

> status 0のレコード解析するbatch処理(10分感覚とかで定期実行かAPI制限を見ながらなのか)

このissue では上記の処理を実装するということで👍

**Comment by TsutomuNakamura** [comment]
自分はこちらをやっておきます👷‍♂️
