### ISSUE TITLE
検索ワードのブラックリストのチェック

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#132]
検索ワードがネガティブ系や卑猥系、差別用語を含んでいる場合は解析できないようにする。

ブラックリストのメンテンナンスを考慮すると、DBにマスタデータを持たせたほうが良さそうです。

**Comment by TsutomuNakamura** [comment]
こちらのDB テーブル定義については以下のような感じどうでしょう？
```
* black_analysis_words
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| Field               | Type                | Null | Key | Default           | Extra                                         |
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
| id                  | bigint(20) unsigned | NO   | PRI | NULL              | auto_increment                                |
| analysis_word       | varchar(255)        | NO   |     | NULL              | UNIQUE                                        | 解析ワード(重複禁止、インデックス貼る)
| availability        | tinyint(4)          | NO   |     | 0                 |                                               | 0: 有効, 1: 無効。無効なやつはブラックリストとして振る舞わない
| insert_date         | datetime            | NO   |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED                             |
| update_date         | datetime            | NO   |     | CURRENT_TIMESTAMP | DEFAULT_GENERATED on update CURRENT_TIMESTAMP |
+---------------------+---------------------+------+-----+-------------------+-----------------------------------------------+
```
※id 消してanalysis_word をプライマリキーにしても良い🤔？ id の無いテーブルって一般的でしょうか？

**Comment by nsuzuki7713** [comment]
ありがとうございます！！いくつかコメントをしました！
よろしくお願いします🙇‍♂️

- idがないテーブルは見たことないので、連番付与で良さそうです！！
- `analysis_word ` → `analysis_ng_word` NGワードであることを明示しておきました。どうでしょう？
-  `availability` は0と1を取るのでtinyint(1) でも良さそうです。
- `availability` → `is_availability`、`availability_flag` booleanっぽい名称はどうでしょうか？

**Comment by TsutomuNakamura** [comment]
> idがないテーブルは見たことないので、連番付与で良さそうです！！
> analysis_word → analysis_ng_word NGワードであることを明示しておきました。どうでしょう？
> availability は0と1を取るのでtinyint(1) でも良さそうです。

了解です。そのようにしましょう。

> availability → is_availability、availability_flag booleanっぽい名称はどうでしょうか？

個人的にはdelete_flag 等の名称とあわせて`availability_flag` が良いと思います。

こんな感じで職人やっておきますか 👨‍🔧!?

**Comment by nsuzuki7713** [comment]
職人お願いしまぁぁぁす！！ 👨‍🔧 👨‍🔧

**Comment by TsutomuNakamura** [comment]
👨‍🔧👨‍🔧👨‍🔧👨‍🔧👨‍🔧

**Comment by TsutomuNakamura** [comment]
NG ワードの登録についてですが、CSV 等で一覧を用意しておいてアプリ起動時に読み込ませるような処理実装しておこうと思いますが、あっていますか！？

**Comment by nsuzuki7713** [comment]
OKです！！お願いします！

**Comment by TsutomuNakamura** [comment]
了解です！そのように実装する処理を考えておこうと思います。
