### ISSUE TITLE
front からのキャメルケースのリクエストに対応する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#134]
フロント側issue の派生: https://github.com/nsuzuki7713/a6s-cloud-front/issues/85

フロント側から飛んできたキャメルケースのkey をスネークケースに変換する処理を追加する。

**Comment by TsutomuNakamura** [comment]
自分でこのあたり対応しようと思いますが、良いモジュール等みつかりませんでした…。何かあれば教えてください。
ひとまずreplace 使うとキーを一括して入れ替えするようなことはできそうです。
https://stackoverflow.com/a/23074350

**Comment by nsuzuki7713** [comment]
確かにいい感じのないですね。。
`$request->query` に入っている値を取り出す際はキャメルケースべた書きでもいいのかなと思いました。

**Comment by TsutomuNakamura** [comment]
ちょっと挑戦してみても良いですか😎！？
だいぶ昔に`Access-Control-Allow-Origin` ヘッダ入れる対応した時にMiddleware 作成したのですが、そこに処理いれたらもしかしたら…！

https://github.com/nsuzuki7713/a6s-cloud-backend/blob/c71310efdea88f910e0471a01c13ac48bff53deb/a6s-cloud/app/Http/Middleware/Cors.php#L1-L19

**Comment by nsuzuki7713** [comment]
はい！！ぜひお願いします！！👨‍🔧
