### ISSUE TITLE
DB 名を決める

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#17]
#2 にてテーブル設計をしましたが、そういえばDB 名を決めていなかったような気がします。
```a6s_cloud``` とかどうでしょうか？

**Comment by nsuzuki7713** [comment]
異議なしです！！
a6s_cloudの名前に段々と愛着が湧いてきました😊

**Comment by TsutomuNakamura** [comment]
了解です。その他異論なければ…```a6s_cloud``` で行きましょう。

**Comment by tokidrill** [comment]
# LGTM

**Comment by nsuzuki7713** [comment]
このissueって閉じられそうですかね？？

**Comment by TsutomuNakamura** [comment]
すみません。レスポンス遅れました。
本issue クローズで大丈夫だと思います。しばらく待って誰も異論無さそうであれば自分の方でクローズしておきます🙆‍♂️
