### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#2]

**Comment by nsuzuki7713** [comment]
DB設計案です
https://docs.google.com/spreadsheets/d/1yKhZl0ISlI6fhFIjqpVFvrnn9nDJPN232Z2RQCOOH7Q/edit?usp=sharing

ワイアー画面を元に作成しています。
https://a6s-cloud.kibe.la/notes/1

レビューやコメントをお願いします！！

**Comment by tokidrill** [comment]
テーブル名が `RESULTS` だと、所見の人には曖昧な気がします。
僕だったら、`xxx_RESULTS`  のような形でprefixをつけたくなるのですが、どうでしょうか？

**Comment by tokidrill** [comment]
上記に付随してテーブル名が変わるとしたら`RESULT_ID` も変わってくる感じになるでしょうか？？
しかし、命名が長ったらしくなるのもスマートでないので考えものですね…

**Comment by nsuzuki7713** [comment]
RESULTS → ANALSIS_RESULTS
RESULT_ID → ANALSIS_RESULT_ID
に変更しました！！
これぐらいの名称の長さは許容範囲な気がします😀

**Comment by tokidrill** [comment]
`LOOK GOOD FOR ME`

**Comment by TsutomuNakamura** [comment]
遅くなりました。DB 設計ありがとうございます！自分からは

* "ステータス"に実行失敗のステータス(あと実装する場合はキャンセルのステータスも)がほしいと思いました
* "wordcloud画像"をBLOB とする場合、入力例にある値はbase64 でない形式(0x8ff00... のようなバイナリ形式？)になると思います
* TIMESTAMP 型、DATETIME 型を統一したほうが良いと思いました

3 つ目についてはご相談があるのですが、DATETIME 型に合わせる感じがよいしょうか(？)。
その場合、格納する時間はUTC 形式に統一する等のルール決めはいかがでしょうか？
(日本にいる人間しか使わない想定であればJST で格納するでもOK と思います)

細かくて申し訳ありませんが、ご確認お願いします🙇‍♂️。

**Comment by nsuzuki7713** [comment]
> TIMESTAMP 型、DATETIME 型を統一したほうが良いと思いました

更新日時はレコードが更新された日付でupdateしたほうがいいかなと思い、TIMESTAMPにしました。
DATETIMEだと明示的に値を渡さないと更新されない。
https://qiita.com/ykawakami/items/2449a24e3b82ff0cbab6

ただ、今回はupdate処理はほぼないので、DATETIMEに統一したほうがいいんですかね？？
格納する時間は一旦、JST統一でいいかなと思っています。

> ステータス"に実行失敗のステータス(あと実装する場合はキャンセルのステータスも)がほしいと思いました

追加します！！

> "wordcloud画像"をBLOB とする場合、入力例にある値はbase64 でない形式(0x8ff00... のようなバイナリ形式？)になると思います

変更します！！

**Comment by TsutomuNakamura** [comment]
> DATETIMEだと明示的に値を渡さないと更新されない。
> クライアンツールなどでdelete_flagを修正した場合もTIMESTAMPなら日付がupdateされます。

この点については考慮がぬけていました。それであればTIMESTAMP 型が良いと思います👍。なるほど、TIMESTAMP は値を指定しなかった場合に現在時刻を入れる、みたいなことができるんですね🤔。
TIMESTAMP はタイムゾーンもJST統一の件も了解しました！

**Comment by TsutomuNakamura** [comment]
typo です。。

> TIMESTAMP はタイムゾーンもJST統一の件も了解しました！

↓　↓　↓
DATETIME はタイムゾーンもJST統一の件も了解しました！

**Comment by nsuzuki7713** [comment]
ありがとうございます😊
最初はこの構造でスタートしましょう！
よっしゃー、クローズ

**Comment by TsutomuNakamura** [comment]
新しいLaravel, MySQL を触っていて気付いたことです。
* MySQL 8 あたりからtimestamp 型もON UPDATE CURRENT_TIMESTAMP を明示的につけないとレコード更新時に自動でタイムスタンプが更新されなくなった(ようにみえる)
→ datetime 型とそれほど違いが無くなってしまった感じです。なおとさんの示してくださったリンクの記事も5.6 系では同じ動きをしましたが、8 系では自動的に更新されませんでした…
* ID はLaravel 5.8 から(?) unsignedBigInteger が標準で使用されるようになった
-> int 型に変更して試してみることも可能ではありそう
* 外部キーANALSIS_RESULT_ID のデータ型も外部キー制約(同じデータ型である必要性)のため、unsignedBigInteger にします？
-> int 型に変更して試してみることも可能ではありそう

MySQL のバージョンを変更するなども考慮に入れて、次回ミーティングあたりに相談とかさせてもらえたら嬉しいです。

**Comment by nsuzuki7713** [comment]
さすがです！！やっぱり触ってみないと分からないですねー

**Comment by TsutomuNakamura** [comment]
はい、触ってみないとわからないです、このあたり🤔。
選択肢はいくらかあるので、対面したときetc にみなさんのご意見きければと！

**Comment by nsuzuki7713** [comment]
#33 でclose
