### ISSUE TITLE
PHPとPythonの役割設計

### ISSUE THREAD

**Issue by tokidrill** [nsuzuki7713/a6s-cloud-backend#22]
* PHPでは解析のCR(UD)を行う。
* Pythonでは形態素解析を行って、画像を生成する

- [ ] Tweet を取得するのはどっち？
- [ ] Vueでグラフを出力する元になるデータを生成(加工)するのはPHPでOK?

**Comment by tokidrill** [comment]
なおとさんの[twitter-analisys](https://github.com/nsuzuki7713/twitter-analysis)を元に、Pythonのgitsubmoduleを作ってそれをLaravelに導入するという方法はどうだろう。
submodule部分でTwitterAPIを叩き、取得した情報をword-cloudライブラリで処理して画像を生成、Twitterから取れた情報を全部Laravel側に返す。
Laravel側では、submoduleから受け取った情報をVueで処理しやすい形に加工、Vueに返すという設計です。

submoduleとしてPythonのコードをパッケージ化してしまえば、またword-cloud使いたいってなったときに使えて便利かなと思って思いつきました。

素人考えなんですが、この設計無理ないですかね？
実現性もそうですが、コストとか性能も考慮できてるかアドバイスもらえると嬉しいです。

**Comment by TsutomuNakamura** [comment]
はい、自分も当初似たようなことを構想していました。
開発環境ではlaradock のworkspace コンテナからなおとさんのPython ライブラリを叩くような感じでいけるのかなー…とゆるく考えています。
あとはなおとさんのPython のやつ見たら、Twitter のトークンが必要みたいですが誰のを使いましょう🙄？

**Comment by nsuzuki7713** [comment]
php側でtweetデータ取得をして、pythonはwordcloud処理用バッチでもいいかなと思いました。
tweetデータのDB登録をpython側で実装するとsubmoduleとしては少し重いかなと思いました🤔
でもマイクロサービスの観点だと分けたほうが良い気もします。
これは対面でも色々話してみたい話題です😊

Twitter のトークンはa6s-cloudでアカウントを取ったのでそれを使いましょう。
この前、アカウントは取れたのですが、twitter apiまで取れませんでした。。(確認用メールが飛んでこなかった)
issueには積んでるので、時間ある時にやっておきますー

**Comment by TsutomuNakamura** [comment]
> Twitter のトークンはa6s-cloudでアカウントを取ったのでそれを使いましょう。

なるほど、それが良さそうですね。
確かに対面で話してみたい話題です。次の議題になりそうです。

**Comment by tokidrill** [comment]
> tweetデータのDB登録をpython側で実装するとsubmoduleとしては少し重いかなと思いました🤔

確かにこれはそうですね。
一度機能を整理して、どこでどのように処理を行うかを明らかにしながら決めていきましょう。

**Comment by TsutomuNakamura** [comment]
> Tweet を取得するのはどっち？

PHP で取得する。

> Vueでグラフを出力する元になるデータを生成(加工)するのはPHPでOK?

PHP で生成(加工)する。

Python はWordCloud の画像生成に専念。PHP で取得したツイートを(DB に登録した上で)Python 側に渡して画像を取得する、という感じでよろしかったでしょうか😎？

**Comment by nsuzuki7713** [comment]
>Python はWordCloud の画像生成に専念。PHP で取得したツイートを(DB に登録した上で)Python 側に渡して画像を取得する、という感じでよろしかったでしょうか😎？

→OKです！！PythonのWordCloud はtextファイルのパスを受け取り、画像を生成して、パスを返す感じです。

**Comment by nsuzuki7713** [comment]
nsuzuki7713/a6s-cloud-front/issues/12
で話し合った。

## PHP
- ツイートデータ取得
- 加工、集計

## python
- WordCloud の画像生成
