### ISSUE TITLE
APIのクロスオリジン問題解消

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#23]
ブラウザからだと、クロスオリジン問題でデータ取得ができなかったです。
サーバ側でクロスオリジンの設定が必要そうです。

フロント側の connect_api_axios ブランチでたぶん動作確認できます。。

一旦、つとむさんをアサインしてます🙇‍♂️

<img width="885" alt="2019-02-24 23 43 39" src="https://user-images.githubusercontent.com/34429882/53300687-0f04e000-388e-11e9-96a3-c0b22614a3d5.png">

**Comment by TsutomuNakamura** [comment]
なるほど了解です。例のヘッダをつけるようにすればイイんですね…。チョット調べておきます。

**Comment by nsuzuki7713** [comment]
#24 で対応完了です。
