### ISSUE TITLE
DBのエンコードの設定を変更する必要あり

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#38]
MySQLで`SQLSTATE[HY000]: General error: 1366 Incorrect string value` というエラーが出た。
原因は絵文字がエンコーディングができなかったから。

とりあえず、ローカル環境で下記のEncodingをutf8mb4に修正した。
- tweet->user_name
- tweet->user_account
- tweet->text

<img width="1183" alt="スクリーンショット 2019-03-30 16 22 22" src="https://user-images.githubusercontent.com/34429882/55273001-a4b9e200-5308-11e9-99cc-1afc1eaff11a.png">

## 対応方針
migrationファイルにEncodingをutf8mb4にする設定を書く（設定できるかは不明）

### 参考URL
https://qiita.com/edisonthk/items/03d7023fb53006a7c83e
http://ryoichi0102.hatenablog.com/entry/2016/12/27/081642

**Comment by TsutomuNakamura** [comment]
以下のページ見ると、migration ファイルにutf8mb4 にする設定を書くことはできそうです。

https://stackoverflow.com/questions/43003301/changing-laravel-mysql-to-utf8mb4-for-emoji-support-in-existing-database

ちょっと、自分の手元で確認してみます👨‍🏭(職)

**Comment by nsuzuki7713** [comment]
#45 の対応でクローズです🥳

**Comment by TsutomuNakamura** [comment]
ありがとうございます😍
