### ISSUE TITLE
analysis_resultsテーブルにURLのカラムを追加する

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#41]

**Comment by nsuzuki7713** [comment]
RETWEET_COUNTも追加する
[DBの設計書](
https://docs.google.com/spreadsheets/d/1yKhZl0ISlI6fhFIjqpVFvrnn9nDJPN232Z2RQCOOH7Q/edit#gid=0)にもないので、こちらにも追加する

**Comment by nsuzuki7713** [comment]
僕はこれをやっておきます。足りないカラムを足します。
新たにマイグレーションファイルを追加して、カラムを追加しようと思います

**Comment by TsutomuNakamura** [comment]
宜しくおねがいします👨‍🔧(職人)
