### ISSUE TITLE
AnalysisRequestsControllerでパラメータにバリデーションする

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#46]
下記を参考にして必須チェックを行う。桁数や日付が必要かは検討
このタスクでは必須チェックのみにして、別のバリデーションが必要ならissueを切りましょうか。
nsuzuki7713/a6s-cloud-front/issues/42

**Comment by tokidrill** [comment]
これやりまーす

**Comment by tokidrill** [comment]
ひとまずバリデーションを実装しました。
参考: https://readouble.com/laravel/5.8/ja/validation.html

問題がひとつありまして、現在の実装では、バリデーションエラー検知すると自動でリダイレクトのレスポンスが発行されます。
※ https://readouble.com/laravel/5.8/ja/validation.html
```バリデーションに失敗すると、例外が投げられ、ユーザーに対し自動的に適切なエラーレスポンスが返されます。伝統的なHTTPリクエストの場合は、リダイレクトレスポンスが生成され、(略)```
なので、オリジナルのバリデータが必要になりそうです。
そして、エラー検知した場合はどのようなレスポンスにするかということも決める必要がありそうです。

それといくつか質問があるんですが… ↓
①
```Illuminate\Support\Facades\Request``` ファサードを使っているようなのですが、これって意図ありますか？？
よく調べてないですが、 ```Illuminate\Http\Request``` に統一できそうです。
(こっちの方が便利っぽい。ドキュメントでもこれ使ってました。)
②
```use Illuminate\Support\Facades\Storage;``` これなんですが、 ```use Storage``` で大丈夫な気がします。何か意図があってこうなってますか？？
※ https://readouble.com/laravel/5.8/ja/facades.html より 
```Laravelのファサードはすべて、Illuminate\Support\Facades名前空間下で定義されています。ですから、簡単にファサードへアクセスできます。```

**Comment by tokidrill** [comment]
リダイレクトさせないバリデーションに関しては、これが参考になりそう…？
https://qiita.com/rana_kualu/items/77134af5477d27bf2cc2

**Comment by nsuzuki7713** [comment]
最初は必須チェックのみで自動レスポンスで良さそうです！！エラーコードを見て、フロントでメッセージは制御しましょうか。
オリジナルバリデーションが必要になったら、その時対応しましょう！！

質問①②は僕は特に意図ないですねー。たぶんコピペで持ってきてます😇
このissueで対応するか、issueを切って別で対応するかお任せします！！
あっでも、他のコントローラも対応する必要があるならissue切って、別対応した方が良いのか🤔

**Comment by TsutomuNakamura** [comment]
近い記憶ですと…Storage に関しては確かにサンプルで目についたものをすぐ書いただけなので、短く描けるならそちらのほうが良いかもですね。修正お願いしたいです🤗
