### ISSUE TITLE
AnalysisRequestsControllerでwordcloud用のテキストファイルを作成

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#50]
textファイルはこんな感じ。
https://raw.githubusercontent.com/nsuzuki7713/a6s-cloud-batch/master/test_data/tweet.txt

`$value->text` をappendしていく形
保存場所はファイル名は暫定的で大丈夫です。

**Comment by TsutomuNakamura** [comment]
調べておきます👨‍🏭
