### ISSUE TITLE
wordcloud 用のtweet データファイルを作成する前に、そのファイルが既に作成されていないかチェックすべき

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#54]
wordcloud 用のtweet データファイルを作成する前に、そのファイルが既に存在しているかをチェックして、既に存在するならファイル名を変更してリトライもしくはエラーとするようにする。

参考:
https://github.com/nsuzuki7713/a6s-cloud-backend/pull/53
https://github.com/nsuzuki7713/a6s-cloud-backend/blob/8ee8cf1169ffa0065f89b21878a5d7d73fa69182/a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php#L32

**Comment by nsuzuki7713** [comment]
UUIDでファイル作成しているので、こちらは一旦対応せずにcloseでも宜しいですか？

[UUID(v4) がぶつかる可能性を考えなくていい理由](https://qiita.com/ta_ta_ta_miya/items/1f8f71db3c1bf2dfb7ea)
[UUIDはなぜ、分散環境で好き勝手に生成しても衝突しないのか。RFC4122規格とUUIDの性質。](http://blog.katty.in/5124)

>「1兆個のUUIDを生成しても、生成したUUIDが重複する確率は、隕石が頭に降ってくる確率より低い」ということ

→😳

**Comment by TsutomuNakamura** [comment]
調査ありがとうございます！
ということはチェック処理はいらないですかね。
重複するより前にDB が一杯にならないか、ディスクが一杯にならないかを心配したほうがよさそうですね😅

**Comment by nsuzuki7713** [comment]
tweetテーブルが定期的に削除とか必要ですかねー
画像もS3を検討もありそうです！
別issueで検討しましょう( ﾟ∀ﾟ)o彡°

**Comment by TsutomuNakamura** [comment]
そうですね！確かにLaravel のStorage 機能でありましたよねS3 それ使うもありだと思います👍

**Comment by TsutomuNakamura** [comment]
別issue で決めることになったためクローズ。
