### ISSUE TITLE
a6s-cloud-batch 処理成功後に、wordcloud 用のtweet データファイルを削除する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#55]
a6s-cloud-batch 処理成功後に、wordcloud 用のtweet データファイルを削除する処理を追加する

参考:
https://github.com/nsuzuki7713/a6s-cloud-backend/pull/53
https://github.com/nsuzuki7713/a6s-cloud-backend/blob/8ee8cf1169ffa0065f89b21878a5d7d73fa69182/a6s-cloud/app/Http/Controllers/AnalysisRequestsController.php#L33

**Comment by nsuzuki7713** [comment]
これやっておきまーす
