### ISSUE TITLE
Twitter API キーの管理方法の決定

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#58]
Twitter API キーの管理方法を決める必要がある。
普通にgit にコミットしてしまうと、誰でも見ることができてセキュリティ的に良くないので、別の方法を考える必要がある。

**Comment by nsuzuki7713** [comment]
`.env.example` ファイルにsampleで書いておくのはどうでしょうか？

**Comment by TsutomuNakamura** [comment]
レスポンスありがとうございます。
そうですね、それで管理する感じで良いと思います。デプロイする時に正式なキーを入れるという感じですよね？

`.env.example` ファイルにsample 書かれたやつのプルリクのマージを持ってクローズでどうでしょう。

**Comment by nsuzuki7713** [comment]
>デプロイする時に正式なキーを入れる

僕もこの認識です！！

>sample 書かれたやつのプルリクのマージを持ってクローズでどうでしょう。

こちらもOKです！！他のissue対応したときに一緒に入れちゃいましょうかー
もしかしたら直近だとつとむさんがプルリク出しそう🤔

**Comment by TsutomuNakamura** [comment]
あ、今時分は#49 の方考えているので、しばらくは無いです。もし対応することになったら宣言してから対応するようにします🙋‍♂️(笑)

**Comment by nsuzuki7713** [comment]
ちょうどwebhookも試したので、僕の方でプルリク作成しておきますね！
