### ISSUE TITLE
AnalysisRequestsControllerで画像をbase64変換して保存する処理

### ISSUE THREAD

**Issue by nsuzuki7713** [nsuzuki7713/a6s-cloud-backend#60]

**Comment by TsutomuNakamura** [comment]
しらべている範囲ですと、DB のimage の型はBLOB 系なのでbase64 でString 型に変換せずにバイナリのまま保存できそうです。
ただ、詳細結果画面などでJSON 使ってネットワーク経由で画像を渡す時は文字列型にしてあげないとJSON が崩れてしまうので、base64 で文字列型にしてあげる必要がありそうです。

詳細結果画面リクエスト -> DB からWord Cloud イメージ取得(binary) -> base64 でString 型に変換 -> JSON でフロントへレスポンス

**Comment by TsutomuNakamura** [comment]
これからの方針については#92 で会話中
