### ISSUE TITLE
Word Cloud で使用するフォントを正式決定する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#66]
#12 に関連して、Word Cloud で使用するフォントを正式決定したいです。

https://github.com/nsuzuki7713/a6s-cloud-batch/blob/8b7d69ebb1f59b853695178b58edc842a49bdc70/src/createWordCloud.py#L46

**Comment by nsuzuki7713** [comment]
こだわりないので　Linux？で動くやつなら何でもよいです🙆‍♂️

**Comment by TsutomuNakamura** [comment]
連絡ありがとうございます。
ということは一旦サンプルと同じでRictyDiminished-Bold 使う方向で行きましょうか💪

その他ツッコミなければクローズしておきます。

**Comment by TsutomuNakamura** [comment]
https://github.com/edihbrandon/RictyDiminished

**Comment by nsuzuki7713** [comment]
異議なしです！！closeで大丈夫です！

**Comment by TsutomuNakamura** [comment]
クローズします！！
