### ISSUE TITLE
Twitter API から取得したTweet 日時(DB のカラム名created_at)がUTC になっている

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#69]
#68 のレビューをしている時に気付いた内容

Twitter API からデータを取得すると、Tweet された時刻(created_at)がUTC になっているように見える。
DB にJST で保存するかUTC で保存するか決定したい。

**Comment by nsuzuki7713** [comment]
JSTの方がSQL検索をする際に良さそうな気もしていますが、どうなんでしょう？
基本的にはJSTのイメージを持ってました。

**Comment by TsutomuNakamura** [comment]
コメ🐜がとうございます。
はい、自分もJST のイメージです。となると、`Tweeter API からデータ取得 -> UTC からJST に変換 -> DB に保存` という処理の追加が必要に感じています。

**Comment by TsutomuNakamura** [comment]
では、取得したTweet の時刻をJST に変換するという新issue を建てておこうと思います👐
