### ISSUE TITLE
Word Cloud 実行のためのPython 環境を構築する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#78]
laradock の環境を確認すると、python3 はインストールされているようだが、pip コマンドがインストールされていない。
```
laradock@edd6172d5006:~$ python3 --version
Python 3.5.2
laradock@edd6172d5006:~$ pip
-su: pip: command not found
laradock@edd6172d5006:~$ find / -name pip 2> /dev/null
laradock@edd6172d5006:~$ 
```
Word Cloud に必要なモジュールをインストールしてWord Cloud を実行できるようにpython とpip 環境を整備する必要がある。

関連issue: #12

**Comment by TsutomuNakamura** [comment]
laradock の設定ファイルにpython をインストールするオプションがあるように見える。
```
WORKSPACE_INSTALL_PYTHON=false
```
これをチョット試してみようと思います🤩

**Comment by TsutomuNakamura** [comment]
これをtrue にして実行してみたらpython2 系がインストールされました。
今後のメンテナンスのことを考えるとpython3 系のほうが良いと思うのでbuild.sh 内で独自にpython3 環境を入れる方針で、一旦対応したいと思います。

**Comment by nsuzuki7713** [comment]
了解です！！
おぉ、これはコントリビュータになるチャンス！？笑

**Comment by TsutomuNakamura** [comment]
な、なるほど…根本から変えてしまえと！！😳
