### ISSUE TITLE
README 追加

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#9]
* このプログラムの役割
* 簡単な使い方
* フロントエンドリポジトリへのリンク
* ライセンスの明示
あたりの記述があれば良いかもしれません。
(異論大歓迎です)

**Comment by tokidrill** [comment]
2/17 0時頃 slackの#チーム開発 チャネルで以下のように決定した。

• frontリポジトリのREADMEに開発理念や運用方法を書き、backendのリポジトリへのリンクを貼る
• backendリポジトリのREADMEにはfront側のREADMEのリンクのみを貼る
• kibelaに記事を作った場合は、適切な位置にリンクを貼る

**Comment by tokidrill** [comment]
考えてみたら、技術要件はPythonも書くべきだし、バージョンも書くべき。
そしてバージョンなどは頻繁に変更されるものでないにしろ、複数箇所変更するのは面倒なので、front側にまとめて書くべきか。
まぁ、問題になったら削除でいいか。とりあえずはこれで運用してみよう。

**Comment by tokidrill** [comment]
文字化けしていたので技術要件の削除と併せて修正。
…のはずが文字化けが治らない。
おお、Tokiよ。markdownでハマるとは情けない。

**Comment by TsutomuNakamura** [comment]
ありがとうございます！
あ、文字化け自分も今コメントしようとしていました…。どうもです！

![p](https://user-images.githubusercontent.com/10674169/52902020-3c2e0e80-324e-11e9-8ed1-1e3deb66533c.png)

**Comment by tokidrill** [comment]
お騒がせしましたが、文字化け直ったのでcloseします。
修正箇所、他の利用案などありましたら適宜openしてください。
