### ISSUE TITLE
Word Cloud 画像がBLOB 上限に引っかかりDB に保存できない

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#92]
BLOB だと64KB 制限がかかっていて、それに対してWord Cloud 画像は数100KB 程なのでエラーになってしまう。

```
String data, right truncated: 1406 Data too long for column 'image' at row 1 (SQL: update `analysis_results` set `image`
```

![p](https://user-images.githubusercontent.com/10674169/56450188-d3066c80-635e-11e9-90b3-70fcb485c5ec.png)

関連issue: #85

**Comment by nsuzuki7713** [comment]
そういう制約が。。
BLOBが無理ならローカルストレージに溜め込む形でしょうか？？

**Comment by TsutomuNakamura** [comment]
あっ、旅行から帰ってきてからレスで構いませんよー😭

確かにローカルストレージに溜め込む方法ありだと思います。
それかMEDIUMBLOB(16MB) に型を変換するかだと思います。

**Comment by TsutomuNakamura** [comment]
### ●ローカルストレージに保存する場合
#### 利点:
* DB の型制限を気にしなくてOK
#### 欠点:
* ファントムファイルができる可能性がでてくる

### ●MEDIUMBLOB に保存する場合
#### 利点:
* ファントムファイルができない
#### 欠点:
* 画像容量が大きくなりすぎると保存できない

簡単に調べた範囲ですと、このような感じでしょうか？
DB テーブルのimage はString 系の型に変更して、ファイルのPATH 情報をもたせるようにしてローカルストレージに保存する形式に変えましょうか…

ひとまずは、旅行楽しんできてください！！

**Comment by nsuzuki7713** [comment]
対応方法ありがとうございます！！どちらも確認しました。
 > ローカルストレージに保存する場合

→ファントムファイルはアンチパターンの分類なんですね。

今回はWord Cloudの画像のみで大きさも想定できるのでトランザクション処理やDBのみで管理できるMEDIUMBLOBを使用したほうが良さそうな気もしましたが、**OGP**するためにはファイルを保存しておいたほうがよいのか🤔

**Comment by TsutomuNakamura** [comment]
なるほど、OGP のこと考えてませんでした。ではローカルストレージに保存する形式が良さそうな気がしてきました。
となると今のDB のimage フィールドはBLOB から文字列型に変更する感じでしょうか👨‍🔧！？

**Comment by nsuzuki7713** [comment]
変更しましょう٩( ᐛ )و

**Comment by TsutomuNakamura** [comment]
Yes 👨‍🔧！ではissue たてておきます。

**Comment by nsuzuki7713** [comment]
ファイルをフロント側から取得する形だと画像をパブリックディスクの設定が必要なんですね。
https://readouble.com/laravel/5.7/ja/filesystem.html

**Comment by TsutomuNakamura** [comment]
あーなるほど！たし🦀。DB にファイルのパス文字列を保存するようにするだけでなく、この対応も必要ですね。
