### ISSUE TITLE
analysis_results テーブルのimage フィールドをString 系のデータ型に変更する

### ISSUE THREAD

**Issue by TsutomuNakamura** [nsuzuki7713/a6s-cloud-backend#97]
Word Cloud 画像をローカルストレージに保管する形式に変更するため、analysis_results テーブルのimage フィールドをString 系の文字列に変更する。
image フィールドにはWord Cloud 画像のPATH(or ファイル名)を保管するようにする。

関連issue: #92

**Comment by TsutomuNakamura** [comment]
こちらは他のフィールドと合わせてVARCHAR 255 で行こうと思います(問題ありましたらコメください)。

**Comment by TsutomuNakamura** [comment]
こちら取り掛かりまーす👨‍🔧

**Comment by nsuzuki7713** [comment]
これは #108 で対応しているので閉じますね！！
